issues:
  - comment: |
      Please add a `type:<issue type>` label to this
      issue.
    label: needs-type
  - comment: "@lswith"
    label: type:test
pulls:
  - comment: |
      Please add a `type:<issue type>` label to this
      issue.
    label: needs-type
  - comment: "@lswith"
    label: type:test
